CCIH/Controllers/GroupController.cs
using CCIH.Entities;
using CCIH.Models;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using static System.Net.Mime.MediaTypeNames;
using System.Windows.Controls.Primitives;
using System.Diagnostics.Eventing.Reader;
using System.Text.RegularExpressions;
using System.Windows.Controls;

namespace CCIH.Controllers
{
    public class GroupController : Controller
    {

        GroupModel GroupModel = new GroupModel();
        StateModel StateModel = new StateModel();
        CourseModel CourseModel = new CourseModel();
        UserModel UserModel = new UserModel();
        ScheduleModel ScheduleModel = new ScheduleModel();


        // GET: Group
        public ActionResult Index()
        {
            try
            {
                return View();
            }
            catch (Exception ex)
            {
                var exept = ex.Message;
                return RedirectToAction("ErrorAdministration", "Error");
            }
            
        }



        [Authorize]
        [HttpGet]
        public ActionResult SetPeople(bool init, long groupIdP)
        {
            try
            {
                var DataStudents = UserModel.SeeAllUserStudentsOutGroup();



                //Groups
                var Group = GroupModel.RequestGroupScrollDown();

                var ComboGroup = new List<SelectListItem>();




                if (init)
                {
                    ComboGroup.Add(new SelectListItem
                    {
                        Text = "Seleccionar Grupo",
                        Value = 0.ToString(),
                        Selected = true
                    });
                }
                else
                {
                    ComboGroup.Add(new SelectListItem
                    {
                        Text = "Seleccionar Grupo",
                        Value = 0.ToString()
                    });
                }

                foreach (var item in Group)
                {
                    if (init)
                    {
                        ComboGroup.Add(new SelectListItem
                        {
                            Text = item.GroupName,
                            Value = item.GroupId.ToString(),

                        });
                    }
                    else
                    {
                        ComboGroup.Add(new SelectListItem
                        {
                            Text = item.GroupName,
                            Value = item.GroupId.ToString(),
                            Selected = true
                        });
                    }

                }
                ViewBag.Group = ComboGroup;


                //Teacher
                var Teacher = UserModel.SeeAllUserTeacher();
                var ComboTeacher = new List<SelectListItem>();


                if (init)
                {
                    ComboTeacher.Add(new SelectListItem
                    {
                        Text = "Sin Profesor",
                        Value = 0.ToString(),
                        Selected = true
                    });
                }
                else
                {

                    var dataGroups = GroupModel.SeeGroupsByGroupId(groupIdP);
                    if (dataGroups.TeacherId == 0)
                    {
                        ComboTeacher.Add(new SelectListItem
                        {
                            Text = "Sin Profesor",
                            Value = 0.ToString(),
                            Selected = true
                        });
                    }
                }

                foreach (var item in Teacher)
                {
                    if (init)
                    {
                        ComboTeacher.Add(new SelectListItem
                        {
                            Text = item.Name + " " + item.LastName,
                            Value = item.EmployeeId.ToString(),

                        });
                    }
                    else
                    {
                        ComboTeacher.Add(new SelectListItem
                        {
                            Text = item.Name + " " + item.LastName,
                            Value = item.EmployeeId.ToString(),
                            Selected = true
                        });
                    }
                }
                ViewBag.Teacher = ComboTeacher;


                //Schedule
                var Schedule = ScheduleModel.RequestScheduleScrollDown();
                var ComboSchedule = new List<SelectListItem>();

                ComboSchedule.Add(new SelectListItem
                {
                    Text = "Sin Horario",
                    Value = 0.ToString(),
                    Selected = true
                });



                foreach (var item in Schedule)
                {
                    ComboSchedule.Add(new SelectListItem
                    {
                        Text = item.Description,
                        Value = item.ScheduleId.ToString(),
                        Selected = true
                    });
                }
                ViewBag.Schedule = ComboSchedule;



                SetPeopleEnt setPeopleEnt = new SetPeopleEnt();

                setPeopleEnt.StudentsOutGroup = DataStudents;

                if (!init)
                {
                    var dataGroup = GroupModel.SeeGroupsByGroupId(groupIdP);
                    setPeopleEnt.GroupEnt = dataGroup;

                }


                if (!init)
                {
                    if ((int)Session["MensajePositivo"] == 1)
                    {

                        ViewBag.MsjPantallaPostivo = "El Estudiante fue asignado de manera correcta";
                    }


                    if ((int)Session["MensajeNegativo"] == 2)
                    {

                        ViewBag.MsjPantallaNegativo = "No se ha podido asignar el Estudiante";
                    }

                    if ((int)Session["MensajePositivo"] == 3)
                    {

                        ViewBag.MsjPantallaPostivo = "El Profesor fue asignado de manera correcta";
                    }


                    if ((int)Session["MensajeNegativo"] == 4)
                    {

                        ViewBag.MsjPantallaNegativo = "No se ha podido asignar el Profesor";
                    }

                    if ((int)Session["MensajeNegativo"] == 5)
                    {

                        ViewBag.MsjPantallaNegativo = "No se ha podido asignar el Estudiante porque excede el maximo de alumnos";
                    }

                }


                return View(setPeopleEnt);
            }
            catch (Exception ex)
            {
                var exept = ex.Message;
                return RedirectToAction("ErrorAdministration", "Error");
            }
            
        }


        /*-----------------------------------------------------------------------------------------------------------*/

        [Authorize]
        [HttpGet]
        public ActionResult RemovePeople(bool init, long groupIdP)
        {

            try
            {
                var DataStudents = UserModel.SeeAllUserStudentsInGroupID(groupIdP);
                var dataGroups = GroupModel.SeeGroupsByGroupId(groupIdP);


                //Groups
                var Group = GroupModel.RequestGroupScrollDown();

                var ComboGroup = new List<SelectListItem>();




                if (init)
                {
                    ComboGroup.Add(new SelectListItem
                    {
                        Text = "Seleccionar Grupo",
                        Value = 0.ToString(),
                        Selected = true
                    });
                }
                else
                {
                    ComboGroup.Add(new SelectListItem
                    {
                        Text = "Seleccionar Grupo",
                        Value = 0.ToString()
                    });
                }

                foreach (var item in Group)
                {
                    if (init)
                    {
                        ComboGroup.Add(new SelectListItem
                        {
                            Text = item.GroupName,
                            Value = item.GroupId.ToString(),

                        });
                    }
                    else
                    {
                        ComboGroup.Add(new SelectListItem
                        {
                            Text = item.GroupName,
                            Value = item.GroupId.ToString(),
                            Selected = true
                        });
                    }

                }
                ViewBag.Group = ComboGroup;


                //Teacher
                var Teacher = UserModel.SeeAllUserTeacher();
                var ComboTeacher = new List<SelectListItem>();


                if (init)
                {
                    ComboTeacher.Add(new SelectListItem
                    {
                        Text = "Sin Profesor",
                        Value = 0.ToString(),
                        Selected = true
                    });
                }
                else
                {


                    if (dataGroups.TeacherId == 0)
                    {
                        ComboTeacher.Add(new SelectListItem
                        {
                            Text = "Sin Profesor",
                            Value = 0.ToString(),
                            Selected = true
                        });
                    }
                }


                foreach (var item in Teacher)
                {


                    if (init)
                    {
                        ComboTeacher.Add(new SelectListItem
                        {

CCIH/Views/Group/ShowGroups.cshtml
@{
    ViewBag.Title = "ShowGroups";
    Layout = "~/Views/Shared/_Layout_Administration.cshtml";
}


<heah>
    <link rel="stylesheet" href="~/assets/Administration/css/datatable/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="~/assets/Administration/css/datatable/buttons.dataTables.min.css" />
    <link rel="stylesheet" href="~/assets/Administration/css/datatable/1.5.1_css_dataTables.dateTime.min.css" />

    <script defer src="~/assets/Administration/js/DataTable/code.jquery.com_jquery-3.7.0.js"></script>
    <script defer src="~/assets/Administration/js/DataTable/cdn.datatables.net_1.13.5_js_jquery.dataTables.min.js"></script>
    <script defer src="~/assets/Administration/js/DataTable/cdn.datatables.net_buttons_2.4.1_js_dataTables.buttons.min.js"></script>
    <script defer src="~/assets/Administration/js/DataTable/cdnjs.cloudflare.com_ajax_libs_jszip_3.10.1_jszip.min.js"></script>
    <script defer src="~/assets/Administration/js/DataTable/cdnjs.cloudflare.com_ajax_libs_pdfmake_0.1.53_pdfmake.min.js"></script>
    <script defer src="~/assets/Administration/js/DataTable/cdnjs.cloudflare.com_ajax_libs_pdfmake_0.1.53_vfs_fonts.js"></script>
    <script defer src="~/assets/Administration/js/DataTable/cdn.datatables.net_buttons_2.4.1_js_buttons.html5.min.js"></script>
    <script defer src="~/assets/Administration/js/DataTable/cdn.datatables.net_buttons_2.4.1_js_buttons.print.min.js"></script>
    <script defer src="~/assets/Administration/js/DataTable/2.29.2_moment.min.js"></script>
    <script defer src="~/assets/Administration/js/DataTable/1.5.1_js_dataTables.dateTime.min.js"></script>

    <script defer src="~/assets/Administration/js/DataTable/DataTableGroups.js"></script>

</heah>
<main id="main" class="main">
    <div class="pagetitle">
        <h1>Lista de Grupos</h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="@Url.Action("Index","Admin")">Inicio</a></li>
                <li class="breadcrumb-item">Grupos</li>
            </ol>
        </nav>
    </div><!-- End Page Title -->
    <section class="section">
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">
                        <br />
                        <div class="row">
                            <br>
                            <div class="col-12">
                                <div class="card">
                                    <div class="card-body">
                                        <br>
                                        @if (ViewBag.MsjPantallaPostivo != null)
                                        {
                                            <div id="mensajePositivo" style="text-align:center" class="alert alert-success" role="alert">
                                                @ViewBag.MsjPantallaPostivo
                                            </div>
                                        }
                                        @if (ViewBag.MsjPantallaNegativo != null)
                                        {
                                            <div id="mensajeNegativo" style="text-align:center" class="alert alert-danger" role="alert">
                                                @ViewBag.MsjPantallaNegativo
                                            </div>
                                        }
                                    <table id="DataTable" class="table table-hover" style="width: 100% !important;">
                                        <thead>
                                            <tr>
                                                <th style="text-align:center">Grupo</th>
                                                <th style="text-align:center">Horario</th>
                                                <th style="text-align:center">Profesor</th>
                                                <th style="text-align:center">Fecha Inicio</th>
                                                <th style="text-align:center">Fecha Final</th>
                                                <th style="text-align:center">Maximo Estudiantes</th>
                                                <th style="text-align:center">Numero Estudiantes</th>
                                                <th style="text-align:center">Estado</th>
                                                <th style="text-align:center">Acciones</th>
                                            </tr>
                                        </thead>

                                        <tbody>
                                            @foreach (var item in Model)
                                            {
                                                <tr style="text-align:center">
                                                    <td>@item.GroupName</td>
                                                    <td>@item.ScheduleDescription</td>
                                                    <td>@item.TeacherName</td>
                                                    <td>@item.StartDate.ToString("yyyy-MM-dd")</td>
                                                    <td>@item.EndDate.ToString("yyyy-MM-dd")</td>
                                                    <td>@item.MaxStudentsNumber</td>
                                                    <td>@item.StudentsNumber</td>
                                                    <td>@item.StatusName</td>

                                                    <td style="text-align:center">
                                                        @if (Session["IdRoleUser"].ToString() == "1")
                                                        {
                                                            <a type="submit" class="btn  text-white" style="background-color: #5f81e8; display: inline-flex; margin-bottom: 5px" href="@Url.Action("EditGroup","Group", new { i = item.GroupId })"><i class="bi bi-pencil-square"></i>Editar</a>

                                                        }
                                                        <a type="submit" class="btn  text-white" style="background-color: #5f81e8; display: inline-flex; margin-bottom: 5px" href="@Url.Action("ShowStudentsInGroup","Group", new { groupId = item.GroupId })"><i class="bi bi-person"></i></a>
                                                    </td>
                                                </tr>
                                            }
                                        </tbody>
                                        <tfoot>
                                            <tr>
                                                <th style="text-align:center">Grupo</th>
                                                <th style="text-align:center">Horario</th>
                                                <th style="text-align:center">Profesor</th>
                                                <th style="text-align:center">Fecha Inicio</th>
                                                <th style="text-align:center">Fecha Final</th>
                                                <th style="text-align:center">Maximo Estudiantes</th>
                                                <th style="text-align:center">Numero Estudiantes</th>
                                                <th style="text-align:center">Estado</th>
                                                <th style="text-align:center">Acciones</th>
                                            </tr>
                                        </tfoot>
                                    </table>

                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-12">
                                        <a href="@Url.Action("Index", "Admin")" class="btn btn-secondary">Regresar</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</main><!-- End #main -->

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="~/assets/Administration/js/SetPeople.js"></script>

CCIH/Views/Group/ShowStudentsInGroup.cshtml
@{
    ViewBag.Title = "ShowStudentsInGroup";
    Layout = "~/Views/Shared/_Layout_Administration.cshtml";
}


<head>

    <link rel="stylesheet" href="~/assets/Administration/css/datatable/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="~/assets/Administration/css/datatable/buttons.dataTables.min.css" />
    <link rel="stylesheet" href="~/assets/Administration/css/datatable/1.5.1_css_dataTables.dateTime.min.css" />

    <script defer src="~/assets/Administration/js/DataTable/code.jquery.com_jquery-3.7.0.js"></script>
    <script defer src="~/assets/Administration/js/DataTable/cdn.datatables.net_1.13.5_js_jquery.dataTables.min.js"></script>
    <script defer src="~/assets/Administration/js/DataTable/cdn.datatables.net_buttons_2.4.1_js_dataTables.buttons.min.js"></script>
    <script defer src="~/assets/Administration/js/DataTable/cdnjs.cloudflare.com_ajax_libs_jszip_3.10.1_jszip.min.js"></script>
    <script defer src="~/assets/Administration/js/DataTable/cdnjs.cloudflare.com_ajax_libs_pdfmake_0.1.53_pdfmake.min.js"></script>
    <script defer src="~/assets/Administration/js/DataTable/cdnjs.cloudflare.com_ajax_libs_pdfmake_0.1.53_vfs_fonts.js"></script>
    <script defer src="~/assets/Administration/js/DataTable/cdn.datatables.net_buttons_2.4.1_js_buttons.html5.min.js"></script>
    <script defer src="~/assets/Administration/js/DataTable/cdn.datatables.net_buttons_2.4.1_js_buttons.print.min.js"></script>
    <script defer src="~/assets/Administration/js/DataTable/2.29.2_moment.min.js"></script>
    <script defer src="~/assets/Administration/js/DataTable/1.5.1_js_dataTables.dateTime.min.js"></script>

    <script defer src="~/assets/Administration/js/DataTable/DataTableGroups.js"></script>

</head>

<main id="main" class="main">

    <div class="pagetitle">
        <h1>Estudiantes de Grupo</h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a>Inicio</a></li>
                <li class="breadcrumb-item">Usuarios</li>
                <li class="breadcrumb-item active">Estudiantes de Grupo</li>
            </ol>
        </nav>
    </div><!-- End Page Title -->



    <section class="section">

        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">


                        @if (ViewBag.MsjPantallaPostivo != null)
                        {
                            <div id="mensajePositivo" style="text-align:center" class="alert alert-success" role="alert">
                                @ViewBag.MsjPantallaPostivo
                            </div>
                        }
                        @if (ViewBag.MsjPantallaNegativo != null)
                        {
                            <div id="mensajeNegativo" style="text-align:center" class="alert alert-danger" role="alert">
                                @ViewBag.MsjPantallaNegativo
                            </div>
                        }
                        <br>





                        <div class="row">
                            <div class="col-12">
                                <div class="table-responsive">
                                    <table id="DataTable" class="table table-hover" style="width: 100% !important;">
                                        <thead>
                                            <tr style="text-align:center">
                                                <th>Cedula</th>
                                                <th>Nombre</th>
                                                <th>Apellido 1</th>
                                                <th>Apellido 2</th>
                                                <th>Correo</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach (var item in Model.StudentsInGroup)
                                            {
                                                <tr>
                                                    <td>@item.PersonalID</td>
                                                    <td>@item.Name</td>
                                                    <td>@item.LastName</td>
                                                    <td>@item.SecLastName</td>
                                                    <td>@item.Email</td>


                                                </tr>
                                            }
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                    <br />
                    <div class="row">
                        <div class="col-1">
                            <a href="@Url.Action("ShowGroups","Group")" class="btn btn-secondary">Regresar</a>
                        </div>
                    </div>
                    <br />
                </div>
            </div>
        </div>
    </section>


</main><!-- End #main -->

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>