CCIH/Controllers/TeachersController.cs
using CCIH.Entities;
using CCIH.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Data;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Web;
using System.Web.Mvc;
using Microsoft.Ajax.Utilities;
using System.Windows.Markup.Localizer;

namespace CCIH.Controllers
{
    [Authorize]
    public class TeachersController : Controller
    {
        UserModel model = new UserModel();
        RoleModel modelRole = new RoleModel();
        StateModel modelState = new StateModel();
        TeacherModel modelTeacher = new TeacherModel();


        [HttpGet]
        public ActionResult Index()
        {
        
            var data = modelTeacher.MarkHistory();


            return View(data);

        }

       

     
        public ActionResult RequestTeacher()
        {
            var data = modelTeacher.RequestTeachers();
            
                return View(data);
        }

        [HttpPost]
        public ActionResult TimeMarkTeacher(long i)
        {
            int user = int.Parse(Session["IdUser"].ToString());

            TeacherEnt ent = new TeacherEnt();

            if (i > 0)
            {
                if (i == 1)
                {
                    ent.Office_SH_ID = ent.Office_SH_ID;
                    ent.EntryTime = DateTime.Now;
                    ent.UserId = user;

                    // Obtener el off ID 
                    int office_SH_ID = modelTeacher.EntryMark(ent);

                    // Guardar el off ID 
                    Session["Office_SH_ID"] = office_SH_ID;
                }
                else if (i == 2)
                {
            
                    ent.Office_SH_ID = (int)Session["Office_SH_ID"];
                    ent.ExitTime = DateTime.Now;
                    modelTeacher.ExitMark(ent);

                      
                    
                }
            }

            return View();
        }



        [HttpGet]
        public ActionResult TimeMarkTeacher()
        {
           return View();
        }




       

        [HttpGet]
        public ActionResult AllHours(long i)
        {
            var data = modelTeacher.TotalWorkHours();

            List<TeacherEnt> dato = new List<TeacherEnt>(); // Inicializa dato como una lista vacía

            foreach (var item in data)
                {
                        if (item.UserId == i)
                        {
                         dato.Add(item);
                        }
                }

            dato = dato.OrderByDescending(x => x.EntryTime).ToList();

            return View(dato);
            
        }





        [HttpGet]
        public ActionResult TotalWorkHours()
        {
            var data = modelTeacher.TotalWorkHours();
            return View(data);
        }



        [HttpGet]
        public ActionResult RequestTeachersSchedules()
        {
            var data = modelTeacher.RequestTeachersSchedules();
            return View(data);
        }
    }

}

CCIH/Views/Teachers/AllHours.cshtml
@model IEnumerable<CCIH.Entities.TeacherEnt>


@{
    ViewBag.Title = "AllHours";
    Layout = "~/Views/Shared/_Layout_Administration.cshtml";
}


<head>

    <link rel="stylesheet" href="~/assets/Administration/css/datatable/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="~/assets/Administration/css/datatable/buttons.dataTables.min.css" />
    <link rel="stylesheet" href="~/assets/Administration/css/datatable/1.5.1_css_dataTables.dateTime.min.css" />

    <script defer src="~/assets/Administration/js/DataTable/code.jquery.com_jquery-3.7.0.js"></script>
    <script defer src="~/assets/Administration/js/DataTable/cdn.datatables.net_1.13.5_js_jquery.dataTables.min.js"></script>
    <script defer src="~/assets/Administration/js/DataTable/cdn.datatables.net_buttons_2.4.1_js_dataTables.buttons.min.js"></script>
    <script defer src="~/assets/Administration/js/DataTable/cdnjs.cloudflare.com_ajax_libs_jszip_3.10.1_jszip.min.js"></script>
    <script defer src="~/assets/Administration/js/DataTable/cdnjs.cloudflare.com_ajax_libs_pdfmake_0.1.53_pdfmake.min.js"></script>
    <script defer src="~/assets/Administration/js/DataTable/cdnjs.cloudflare.com_ajax_libs_pdfmake_0.1.53_vfs_fonts.js"></script>
    <script defer src="~/assets/Administration/js/DataTable/cdn.datatables.net_buttons_2.4.1_js_buttons.html5.min.js"></script>
    <script defer src="~/assets/Administration/js/DataTable/cdn.datatables.net_buttons_2.4.1_js_buttons.print.min.js"></script>
    <script defer src="~/assets/Administration/js/DataTable/2.29.2_moment.min.js"></script>
    <script defer src="~/assets/Administration/js/DataTable/1.5.1_js_dataTables.dateTime.min.js"></script>

    <script defer src="~/assets/Administration/js/DataTable/DataTableHoras.js"></script>



</head>

<main id="main" class="main">
    <div class="pagetitle">
        <h1>Lista de Horas</h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="@Url.Action("Index","Admin")">Inicio</a></li>
                <li class="breadcrumb-item">Profesores</li>
                <li class="breadcrumb-item"> Ver Horas</li>
            </ol>
        </nav>
    </div><!-- End Page Title -->

    <section class="section">
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">

                        <div class="container-fluid">

                            @if (ViewBag.MsjPantallaPostivo != null)
                            {
                                <div id="mensajePositivo" style="text-align:center" class="alert alert-success" role="alert">
                                    @ViewBag.MsjPantallaPostivo
                                </div>
                            }
                            @if (ViewBag.MsjPantallaNegativo != null)
                            {
                                <div id="mensajeNegativo" style="text-align:center" class="alert alert-danger" role="alert">
                                    @ViewBag.MsjPantallaNegativo
                                </div>
                            }

                            <br />
                            <!-- General Form Elements -->


                            <div class="row">
                                <div class="col-md-10">
                                    <table border="0" cellspacing="5" cellpadding="5">
                                        <tbody>
                                            <tr>
                                                <td>Fecha Inicio:</td>
                                                <td><input type="text" id="min" name="min" class="form-control"></td>
                                            </tr>
                                            <tr>
                                                <td>Fecha Fin:</td>
                                                <td><input type="text" id="max" name="max" class="form-control"></td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>

                                <div class="col-md-2">
                                    Total de Horas
                                    <input type="text" id="TotalHoras" name="TotalHoras" class="form-control" readonly>
                                </div>
                            </div>

                            <br>

                            <div class="row">
                                <div class="col-12">
                                    <div class="table-responsive">
                                        <table id="DataTable" class="table table-hover text-center" width="100%">
                                            <thead>
                                                <tr>
                                                    <th style="text-align:center">Nombre</th>
                                                    <th style="text-align:center">Entrada</th>
                                                    <th style="text-align:center">Salida</th>
                                                    <th style="text-align:center">Suma de Horas</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                @foreach (var item in Model)
                                                {
                                                    <tr>
                                                        <td>@item.Name</td>
                                                        @if (@item.EntryTime.ToString() == "1/1/0001 00:00:00")
                                                        {
                                                            <td>Pendiente</td>
                                                        }
                                                        else
                                                        {
                                                            <td>@item.EntryTime</td>
                                                        }
                                                        @if (@item.ExitTime.ToString() == "1/1/0001 00:00:00")
                                                        {
                                                            <td>Pendiente</td>
                                                        }
                                                        else
                                                        {
                                                            <td>@item.ExitTime</td>
                                                        }
                                                        <td>@item.TotalHours</td>
                                                    </tr>
                                                }
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                    </div>
                    <div class="row">
                        <div class="col-lg-2 order-lg-3 ms-auto">
                            <button type="button" class="btn btn-secondary m-0 mb-3" onclick="window.history.back();">Regresar</button>
                        </div>
                    </div>


                    </div>
                </div>
                <div class="row">
                    <div class="col-1">
                        <button type="button" class="btn btn-secondary m-0 mb-3" onclick="window.history.back();">Regresar</button>
                    </div>

                </div>
               
            </div>

    </section>
</main><!-- End #main -->
 

CCIH/Views/Teachers/Index.cshtml
@model IEnumerable<CCIH.Entities.TeacherEnt>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout_Administration.cshtml";
}


<head>
    <link rel="stylesheet" href="~/assets/Administration/css/datatable/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="~/assets/Administration/css/datatable/buttons.dataTables.min.css" />
    <link rel="stylesheet" href="~/assets/Administration/css/datatable/1.5.1_css_dataTables.dateTime.min.css" />

    <script defer src="~/assets/Administration/js/DataTable/code.jquery.com_jquery-3.7.0.js"></script>
    <script defer src="~/assets/Administration/js/DataTable/cdn.datatables.net_1.13.5_js_jquery.dataTables.min.js"></script>
    <script defer src="~/assets/Administration/js/DataTable/cdn.datatables.net_buttons_2.4.1_js_dataTables.buttons.min.js"></script>
    <script defer src="~/assets/Administration/js/DataTable/cdnjs.cloudflare.com_ajax_libs_jszip_3.10.1_jszip.min.js"></script>
    <script defer src="~/assets/Administration/js/DataTable/cdnjs.cloudflare.com_ajax_libs_pdfmake_0.1.53_pdfmake.min.js"></script>
    <script defer src="~/assets/Administration/js/DataTable/cdnjs.cloudflare.com_ajax_libs_pdfmake_0.1.53_vfs_fonts.js"></script>
    <script defer src="~/assets/Administration/js/DataTable/cdn.datatables.net_buttons_2.4.1_js_buttons.html5.min.js"></script>
    <script defer src="~/assets/Administration/js/DataTable/cdn.datatables.net_buttons_2.4.1_js_buttons.print.min.js"></script>

    <script defer src="~/assets/Administration/js/DataTable/DataTableUsers.js"></script>


</head>



<main id="main" class="main">



    <div class="pagetitle">
        <h1>Todas las Marcas</h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="@Url.Action("Index","Admin")">Inicio</a></li>
                <li class="breadcrumb-item">Marcas</li>
                <li class="breadcrumb-item">Historial General de Marcas</li>
            </ol>
        </nav>
    </div><!-- End Page Title -->


    <section class="section">
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">

                        <div class="container-fluid">

                            @if (ViewBag.MsjPantallaPostivo != null)
                            {
                                <div id="mensajePositivo" style="text-align:center" class="alert alert-success" role="alert">
                                    @ViewBag.MsjPantallaPostivo
                                </div>
                            }
                            @if (ViewBag.MsjPantallaNegativo != null)
                            {
                                <div id="mensajeNegativo" style="text-align:center" class="alert alert-danger" role="alert">
                                    @ViewBag.MsjPantallaNegativo
                                </div>
                            }

                            <br />
                            <!-- General Form Elements -->


                            @*<div class="row">
                                <div class="col-md-10">
                                    <table border="0" cellspacing="5" cellpadding="5">
                                        <tbody>
                                            <tr>
                                                <td>Fecha Inicio:</td>
                                                <td><input type="text" id="min" name="min" class="form-control"></td>
                                            </tr>
                                            <tr>
                                                <td>Fecha Fin:</td>
                                                <td><input type="text" id="max" name="max" class="form-control"></td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>*@

                            <br>

                            <div class="row">
                                <div class="col-12">
                                    <div class="table-responsive">
                                        <table id="DataTable" class="table table-hover text-center" width="100%">
                                            <thead>
                                                <tr>
                                                    <th style="text-align:center">Cedula</th>
                                                    <th style="text-align:center">Nombre</th>
                                                    <th style="text-align:center">Entrada</th>
                                                    <th style="text-align:center">Salida</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                @foreach (var item in Model)
                                                {
                                                    <tr>
                                                        <td>@item.PersonalID</td>
                                                        <td>@item.Name</td>
                                                        @if (@item.EntryTime == null)
                                                        {
                                                            <td>Pendiente</td>
                                                        }
                                                        else
                                                        {
                                                            <td>@item.EntryTime</td>
                                                        }
                                                        @if (@item.ExitTime == null)
                                                        {
                                                            <td>Pendiente</td>
                                                        }
                                                        else
                                                        {
                                                            <td>@item.ExitTime</td>
                                                        }
                                                    </tr>
                                                }


                                            </tbody>
                                            <tfoot>
                                                <tr>
                                                    <th style="text-align:center">Cedula</th>
                                                    <th style="text-align:center">Nombre</th>
                                                    <th style="text-align:center">Entrada</th>
                                                    <th style="text-align:center">Salida</th>
                                                </tr>
                                            </tfoot>
                                        </table>


                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-1">
                                <button type="button" class="btn btn-secondary m-0 mb-3" onclick="window.history.back();">Regresar</button>
                            </div>
                        </div>
                    </div>
                </div>
                
            </div>
        </div>
    </section>
</main><!-- End #main -->

CCIH/Views/Teachers/RequestTeacher.cshtml
@model IEnumerable<CCIH.Entities.TeacherEnt>


@{
    ViewBag.Title = "JustTeachers";
    Layout = "~/Views/Shared/_Layout_Administration.cshtml";
}


<heah>
    <link rel="stylesheet" href="~/assets/Administration/css/datatable/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="~/assets/Administration/css/datatable/buttons.dataTables.min.css" />
    <link rel="stylesheet" href="~/assets/Administration/css/datatable/1.5.1_css_dataTables.dateTime.min.css" />

    <script defer src="~/assets/Administration/js/DataTable/code.jquery.com_jquery-3.7.0.js"></script>
    <script defer src="~/assets/Administration/js/DataTable/cdn.datatables.net_1.13.5_js_jquery.dataTables.min.js"></script>
    <script defer src="~/assets/Administration/js/DataTable/cdn.datatables.net_buttons_2.4.1_js_dataTables.buttons.min.js"></script>
    <script defer src="~/assets/Administration/js/DataTable/cdnjs.cloudflare.com_ajax_libs_jszip_3.10.1_jszip.min.js"></script>
    <script defer src="~/assets/Administration/js/DataTable/cdnjs.cloudflare.com_ajax_libs_pdfmake_0.1.53_pdfmake.min.js"></script>
    <script defer src="~/assets/Administration/js/DataTable/cdnjs.cloudflare.com_ajax_libs_pdfmake_0.1.53_vfs_fonts.js"></script>
    <script defer src="~/assets/Administration/js/DataTable/cdn.datatables.net_buttons_2.4.1_js_buttons.html5.min.js"></script>
    <script defer src="~/assets/Administration/js/DataTable/cdn.datatables.net_buttons_2.4.1_js_buttons.print.min.js"></script>
    <script defer src="~/assets/Administration/js/DataTable/2.29.2_moment.min.js"></script>
    <script defer src="~/assets/Administration/js/DataTable/1.5.1_js_dataTables.dateTime.min.js"></script>

    <script defer src="~/assets/Administration/js/DataTable/DataTableUsers.js"></script>


</heah>


<main id="main" class="main">
    <div class="pagetitle">
        <h1>Lista de Profesores</h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="@Url.Action("Index","Admin")">Inicio</a></li>
                <li class="breadcrumb-item">Profesores</li>
                <li class="breadcrumb-item">Lista de Profesores</li>
            </ol>
        </nav>
    </div><!-- End Page Title -->

    <section class="section">

        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">
                        </br>

                        @if (ViewBag.MsjPantallaPostivo != null)
                        {
                            <div id="mensajePositivo" style="text-align:center" class="alert alert-success" role="alert">
                                @ViewBag.MsjPantallaPostivo
                            </div>
                        }
                        @if (ViewBag.MsjPantallaNegativo != null)
                        {
                            <div id="mensajeNegativo" style="text-align:center" class="alert alert-danger" role="alert">
                                @ViewBag.MsjPantallaNegativo
                            </div>
                        }


                        <br />
                        <div class="row">
                            <div class="col-12">
                                <div class="table-responsive">
                                    <table id="DataTable" class="table table-hover text-center" width="100%">
                                        <thead>
                                            <tr>
                                                <th style="text-align:center">Cedula</th>
                                                <th style="text-align:center">Nombre</th>
                                                <th style="text-align:center">Apellido</th>
                                                <th style="text-align:center">Segundo Apellido</th>
                                                <th style="text-align:center">Correo</th>
                                                <th style="text-align:center">Acción</th>



                                            </tr>
                                        </thead>
                                        <tbody>

                                            @foreach (var item in Model)
                                                {
                                                    <tr>
                                                        <td>@item.PersonalID</td>
                                                        <td>@item.Name</td>
                                                        <td>@item.LastName</td>
                                                        <td>@item.SecLastName</td>
                                                        <td>@item.Email</td>
                                                  



                                                        <td style="text-align:center">
                                                            <a type="submit" class="btn btn-sm text-white" style="background-color: #5f81e8; display: inline-block; margin-bottom: 5px;" href="@Url.Action("EditUser", "User", new { i = item.UserId })"><i class="bi bi-pencil-square"></i> Editar</a>

                                                            <a type="submit" class="btn btn-sm text-white" style="background-color: #5f81e8; display: inline-block; margin-bottom: 5px; " href="@Url.Action("AllHours", "Teachers", new { i = item.UserId })"><i class="bi bi-search"></i> Ver Horas</a>
                                                        </td>
                                                    </tr>
                                               
                                                    }
                                      
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-2 order-lg-3 ms-auto">
                            <button type="button" class="btn btn-secondary m-0 mb-3" onclick="window.history.back();">Regresar</button>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </section>
</main><!-- End #main -->

CCIH/Views/Teachers/RequestTeachersSchedules.cshtml
@model IEnumerable<CCIH.Entities.TeacherEnt>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout_Administration.cshtml";
}

<head>
    <link rel="stylesheet" href="~/assets/Administration/css/datatable/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="~/assets/Administration/css/datatable/buttons.dataTables.min.css" />
    <link rel="stylesheet" href="~/assets/Administration/css/datatable/1.5.1_css_dataTables.dateTime.min.css" />

    <script defer src="~/assets/Administration/js/DataTable/code.jquery.com_jquery-3.7.0.js"></script>
    <script defer src="~/assets/Administration/js/DataTable/cdn.datatables.net_1.13.5_js_jquery.dataTables.min.js"></script>
    <script defer src="~/assets/Administration/js/DataTable/cdn.datatables.net_buttons_2.4.1_js_dataTables.buttons.min.js"></script>
    <script defer src="~/assets/Administration/js/DataTable/cdnjs.cloudflare.com_ajax_libs_jszip_3.10.1_jszip.min.js"></script>
    <script defer src="~/assets/Administration/js/DataTable/cdnjs.cloudflare.com_ajax_libs_pdfmake_0.1.53_pdfmake.min.js"></script>
    <script defer src="~/assets/Administration/js/DataTable/cdnjs.cloudflare.com_ajax_libs_pdfmake_0.1.53_vfs_fonts.js"></script>
    <script defer src="~/assets/Administration/js/DataTable/cdn.datatables.net_buttons_2.4.1_js_buttons.html5.min.js"></script>
    <script defer src="~/assets/Administration/js/DataTable/cdn.datatables.net_buttons_2.4.1_js_buttons.print.min.js"></script>
    <script defer src="~/assets/Administration/js/DataTable/2.29.2_moment.min.js"></script>
    <script defer src="~/assets/Administration/js/DataTable/1.5.1_js_dataTables.dateTime.min.js"></script>

    <script defer src="~/assets/Administration/js/DataTable/DataTableUsers.js"></script>


</head>




<main id="main" class="main">
    <div class="pagetitle">
        <h1>Lista de Horarios</h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="@Url.Action("Index","Admin")">Inicio</a></li>
                <li class="breadcrumb-item">Profesores</li>
                <li class="breadcrumb-item">Horarios</li>
            </ol>
        </nav>
    </div><!-- End Page Title -->

    <section class="section">

        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">
                        </br>

                        @if (ViewBag.MsjPantallaPostivo != null)
                        {
                            <div id="mensajePositivo" style="text-align:center" class="alert alert-success" role="alert">
                                @ViewBag.MsjPantallaPostivo
                            </div>
                        }
                        @if (ViewBag.MsjPantallaNegativo != null)
                        {
                            <div id="mensajeNegativo" style="text-align:center" class="alert alert-danger" role="alert">
                                @ViewBag.MsjPantallaNegativo
                            </div>
                        }


                        <br />
                        <div class="row">
                            <div class="col-12">
                                <div class="table-responsive">
                                    <table id="DataTable" class="table table-hover text-center" width="100%">
                                        <thead>
                                            <tr>

                                                <th style="text-align:center">Cédula</th>
                                                <th style="text-align:center">Nombre</th>
                                                <th style="text-align:center">Horario</th>
                                           




                                            </tr>
                                        </thead>
                                        <tbody>

                                            @foreach (var item in Model)
                                            {


                                                <tr>

                                                    <td>@item.PersonalID</td>
                                                    <td>@item.Name</td>
                                                    <td>@item.Schedule</td>
                                                </tr>



                                            }



                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-2 order-lg-3 ms-auto">
                            <button type="button" class="btn btn-secondary m-0 mb-3" onclick="window.history.back();">Regresar</button>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </section>
</main><!-- End #main -->